version: '3.8'

services:
  verigpt:
    build: .
    container_name: verigpt
    # Load environment variables from .env file
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
    restart: unless-stopped
